version: '3'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /app/node_modules
    command: /usr/src/app/entrypoint.sh

  mongo:
    image: 'mongo'
    volumes:
      - /home/biotux/data:/data/db
    ports:
      - 27017:27017
