version: '3'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: 'mongo'
    volumes:
      - /home/ubuntu/data:/data/db
    ports:
      - 27017:27017
